pipeline {
    agent {
        docker {
            image 'node:20.9.0-alpine3.18' 
            args '-p 3000:3000' 
        }
    }
    stages {
        stage('Build') { 
            steps {

                sh "cd Restaurant-Monolith/Server"
                sh 'npm install' 
            }
        }
    }
}

